#ifndef __LCD_DRIVER_RPI_H
#define __LCD_DRIVER_RPI_H

//#ifdef RPI
#include <wiringPi.h>


void __LCD_DRIVER_INIT();
void __LCD_DRIVER_WRITE_ZERO_SIG_UP();
void __LCD_DRIVER_WRITE_ZERO_SIG_UP_AFTER();
void __LCD_DRIVER_WRITE_ZERO_SIG_DOWN();
void __LCD_DRIVER_WRITE_ZERO_SIG_DOWN_AFTER();
void __LCD_DRIVER_WRITE_ONE_SIG_UP();
void __LCD_DRIVER_WRITE_ONE_SIG_UP_AFTER();
void __LCD_DRIVER_WRITE_ONE_SIG_DOWN();
void __LCD_DRIVER_WRITE_ONE_SIG_DOWN_AFTER();
void __LCD_DRIVER_WRITE_RESET();
void __LCD_DRIVER_WRITE_RESET_AFTER();

//#endif
#endif /* __LCD_DRIVER_RPI_H */